name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install .[dev]
        pip install flake8 pytest pytest-asyncio
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 hunter tests --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 hunter tests --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
    
    - name: Test with pytest
      env:
        TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
      run: |
        pytest
        
    - name: Build package
      run: python -m build
      
    - name: Check package
      run: |
        pip install twine
        twine check dist/* 